version: "3"

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - /volumn/mysql/data:/var/lib/mysql
    environment:
      # 根目录密码默认123456，可以根据需求改密码
      # 修改的时候要同时修改secret文件的密码
      - MYSQL_ROOT_PASSWORD=123456@signit
      # 这个选项会自动创建数据库
      - MYSQL_DATABASE=block_certs
      - TZ=Asia/Shanghai
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    networks:
      - nginx_network

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - "/data/configdb:/data/configdb"
      - "/data/db:/data/db"
    command: mongod --auth
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root       #初始化管理员用户名和密码
      - MONGO_INITDB_ROOT_PASSWORD=123456@signit
    tty: true
    networks:
      - nginx_network

  web:
    build: .
    command: bash -c "python3 /block_certs_back_end/manage.py makemigrations && python3 /block_certs_back_end/manage.py migrate --noinput && python3 /block_certs_back_end/manage.py runserver 0.0.0.0:8000"
    image: block_certs_back_end
    ports:
      - 8000:8000
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    volumes:
      - /root/block_certs_back_end:/block_certs_back_end
    restart: always
    depends_on:
      - mysql
      - mongo
    networks:
      - nginx_network
  nginx:
    image: nginx:1.13
    build:
      context: .
      dockerfile: /root/block_certs_back_end/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - /root/block_certs_back_end/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
      - mysql
      - mongo
    networks:
      - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge
