# Generated by Django 3.0.3 on 2020-04-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_description', models.CharField(max_length=255)),
                ('certificate_title', models.CharField(max_length=255)),
                ('criteria_narrative', models.CharField(max_length=588)),
                ('cert_id', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('student_pubkey', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('sign_certificate_file', models.CharField(default=None, max_length=255)),
                ('unsign_certificate_file', models.CharField(default=None, max_length=255)),
                ('school_pubkey', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
