# Generated by Django 3.0.3 on 2020-04-09 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
