# Generated by Django 3.0.3 on 2020-04-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='sign_certificate_file',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cert',
            name='unsign_certificate_file',
            field=models.CharField(default='', max_length=255),
        ),
    ]
