# Generated by Django 3.0.3 on 2020-04-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200407_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cert',
            name='sign_certificate_file',
        ),
        migrations.RemoveField(
            model_name='cert',
            name='unsign_certificate_file',
        ),
    ]
