# Generated by Django 3.0.3 on 2020-04-11 07:59

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_cert_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='txid',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 7, 58, 25, 863066, tzinfo=utc)),
        ),
    ]
