# Generated by Django 3.0.3 on 2020-04-11 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200411_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 8, 6, 59, 469495, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cert',
            name='txid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
