# Generated by Django 3.0.3 on 2020-04-12 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200411_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 8, 50, 30, 675371, tzinfo=utc)),
        ),
    ]
