# Generated by Django 3.0.3 on 2020-04-13 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200412_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='school_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 13, 24, 53, 720879, tzinfo=utc)),
        ),
    ]
