# Generated by Django 3.0.3 on 2020-04-19 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200413_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='chain',
            field=models.CharField(default='bitcoin_testnet', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 9, 42, 41, 684442, tzinfo=utc)),
        ),
    ]
