# Generated by Django 3.0.3 on 2020-04-30 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200419_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='refuse_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cert',
            name='chain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 11, 1, 25, 751661, tzinfo=utc)),
        ),
    ]
