# Generated by Django 3.0.3 on 2020-07-11 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_auto_20200711_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 9, 8, 39, 408817, tzinfo=utc)),
        ),
    ]
