FROM nginx
# # Add the Nginx configuration file
# ADD ./nginx/nginx.conf /etc/nginx/nginx.conf
# Copy over static assets from the client application
COPY /root/block-certs-front-end/dist /usr/share/nginx/html