# Generated by Django 3.0.3 on 2020-03-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default=['https://w3id.org/openbadges/v2', 'https://w3id.org/blockcerts/v2'], max_length=255)),
                ('type', models.CharField(default='Profile', max_length=128)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('official_website', models.CharField(max_length=255, unique=True)),
                ('id_url', models.CharField(max_length=255, unique=True)),
                ('revocation_list', models.CharField(max_length=255, unique=True)),
                ('introduction_url', models.CharField(max_length=255, unique=True)),
                ('public_key', models.CharField(max_length=128, unique=True)),
                ('job_title', models.CharField(max_length=128)),
                ('signature_name', models.CharField(max_length=128)),
                ('signature_file_wsid', models.CharField(max_length=128)),
                ('logo_file_wsid', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=225)),
                ('register_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
    ]
