# Generated by Django 3.0.3 on 2020-03-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooltoken',
            old_name='student',
            new_name='school',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
