# Generated by Django 3.0.3 on 2020-03-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_revocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revocation',
            name='type',
        ),
        migrations.AlterField(
            model_name='revocation',
            name='public_key',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
