# Generated by Django 3.0.3 on 2020-04-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20200331_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='revocation',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
